/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedPrecificacaoRouteImport } from './routes/_authenticated/precificacao'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDreRouteImport } from './routes/_authenticated/dre'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalculadoraRouteImport } from './routes/_authenticated/calculadora'
import { Route as AuthenticatedIaIndexRouteImport } from './routes/_authenticated/ia.index'
import { Route as ApiShopeeAuthUrlRouteImport } from './routes/api/shopee/auth-url'
import { Route as AuthenticatedIaConversaIdRouteImport } from './routes/_authenticated/ia.$conversaId'
import { Route as ApiPublicShopeeWebhookRouteImport } from './routes/api/public/shopee/webhook'
import { Route as ApiPublicShopeeWatchdogRouteImport } from './routes/api/public/shopee/watchdog'
import { Route as ApiPublicShopeeSyncProdutosRouteImport } from './routes/api/public/shopee/sync-produtos'
import { Route as ApiPublicShopeeSyncEscrowRouteImport } from './routes/api/public/shopee/sync-escrow'
import { Route as ApiPublicShopeeSyncChatRouteImport } from './routes/api/public/shopee/sync-chat'
import { Route as ApiPublicShopeeSyncCarteiraRouteImport } from './routes/api/public/shopee/sync-carteira'
import { Route as ApiPublicShopeeSyncAdsRouteImport } from './routes/api/public/shopee/sync-ads'
import { Route as ApiPublicShopeeSyncRouteImport } from './routes/api/public/shopee/sync'
import { Route as ApiPublicShopeeResumoDiarioRouteImport } from './routes/api/public/shopee/resumo-diario'
import { Route as ApiPublicShopeeRefreshTokenRouteImport } from './routes/api/public/shopee/refresh-token'
import { Route as ApiPublicShopeeRefreshRouteImport } from './routes/api/public/shopee/refresh'
import { Route as ApiPublicShopeeDbgChatRouteImport } from './routes/api/public/shopee/dbg-chat'
import { Route as ApiPublicShopeeCallbackAdsRouteImport } from './routes/api/public/shopee/callback-ads'
import { Route as ApiPublicShopeeCallbackRouteImport } from './routes/api/public/shopee/callback'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/produtos.lazy').then((d) => d.Route),
)
const AuthenticatedPrecificacaoRoute =
  AuthenticatedPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/precificacao.lazy').then((d) => d.Route),
  )
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/pedidos.lazy').then((d) => d.Route),
)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/notificacoes.lazy').then((d) => d.Route),
  )
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/financeiro.lazy').then((d) => d.Route),
)
const AuthenticatedDreRoute = AuthenticatedDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/dre.lazy').then((d) => d.Route),
)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/dashboard.lazy').then((d) => d.Route),
)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/configuracoes.lazy').then((d) => d.Route),
  )
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/chat.lazy').then((d) => d.Route),
)
const AuthenticatedCalculadoraRoute =
  AuthenticatedCalculadoraRouteImport.update({
    id: '/calculadora',
    path: '/calculadora',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/calculadora.lazy').then((d) => d.Route),
  )
const AuthenticatedIaIndexRoute = AuthenticatedIaIndexRouteImport.update({
  id: '/ia/',
  path: '/ia/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/ia.index.lazy').then((d) => d.Route),
)
const ApiShopeeAuthUrlRoute = ApiShopeeAuthUrlRouteImport.update({
  id: '/api/shopee/auth-url',
  path: '/api/shopee/auth-url',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIaConversaIdRoute =
  AuthenticatedIaConversaIdRouteImport.update({
    id: '/ia/$conversaId',
    path: '/ia/$conversaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ia.$conversaId.lazy').then((d) => d.Route),
  )
const ApiPublicShopeeWebhookRoute = ApiPublicShopeeWebhookRouteImport.update({
  id: '/api/public/shopee/webhook',
  path: '/api/public/shopee/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopeeWatchdogRoute = ApiPublicShopeeWatchdogRouteImport.update({
  id: '/api/public/shopee/watchdog',
  path: '/api/public/shopee/watchdog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopeeSyncProdutosRoute =
  ApiPublicShopeeSyncProdutosRouteImport.update({
    id: '/api/public/shopee/sync-produtos',
    path: '/api/public/shopee/sync-produtos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopeeSyncEscrowRoute =
  ApiPublicShopeeSyncEscrowRouteImport.update({
    id: '/api/public/shopee/sync-escrow',
    path: '/api/public/shopee/sync-escrow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopeeSyncChatRoute = ApiPublicShopeeSyncChatRouteImport.update({
  id: '/api/public/shopee/sync-chat',
  path: '/api/public/shopee/sync-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopeeSyncCarteiraRoute =
  ApiPublicShopeeSyncCarteiraRouteImport.update({
    id: '/api/public/shopee/sync-carteira',
    path: '/api/public/shopee/sync-carteira',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopeeSyncAdsRoute = ApiPublicShopeeSyncAdsRouteImport.update({
  id: '/api/public/shopee/sync-ads',
  path: '/api/public/shopee/sync-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopeeSyncRoute = ApiPublicShopeeSyncRouteImport.update({
  id: '/api/public/shopee/sync',
  path: '/api/public/shopee/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopeeResumoDiarioRoute =
  ApiPublicShopeeResumoDiarioRouteImport.update({
    id: '/api/public/shopee/resumo-diario',
    path: '/api/public/shopee/resumo-diario',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopeeRefreshTokenRoute =
  ApiPublicShopeeRefreshTokenRouteImport.update({
    id: '/api/public/shopee/refresh-token',
    path: '/api/public/shopee/refresh-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopeeRefreshRoute = ApiPublicShopeeRefreshRouteImport.update({
  id: '/api/public/shopee/refresh',
  path: '/api/public/shopee/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopeeDbgChatRoute = ApiPublicShopeeDbgChatRouteImport.update({
  id: '/api/public/shopee/dbg-chat',
  path: '/api/public/shopee/dbg-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopeeCallbackAdsRoute =
  ApiPublicShopeeCallbackAdsRouteImport.update({
    id: '/api/public/shopee/callback-ads',
    path: '/api/public/shopee/callback-ads',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopeeCallbackRoute = ApiPublicShopeeCallbackRouteImport.update({
  id: '/api/public/shopee/callback',
  path: '/api/public/shopee/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calculadora': typeof AuthenticatedCalculadoraRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dre': typeof AuthenticatedDreRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/api/chat': typeof ApiChatRoute
  '/ia/$conversaId': typeof AuthenticatedIaConversaIdRoute
  '/api/shopee/auth-url': typeof ApiShopeeAuthUrlRoute
  '/ia/': typeof AuthenticatedIaIndexRoute
  '/api/public/shopee/callback': typeof ApiPublicShopeeCallbackRoute
  '/api/public/shopee/callback-ads': typeof ApiPublicShopeeCallbackAdsRoute
  '/api/public/shopee/dbg-chat': typeof ApiPublicShopeeDbgChatRoute
  '/api/public/shopee/refresh': typeof ApiPublicShopeeRefreshRoute
  '/api/public/shopee/refresh-token': typeof ApiPublicShopeeRefreshTokenRoute
  '/api/public/shopee/resumo-diario': typeof ApiPublicShopeeResumoDiarioRoute
  '/api/public/shopee/sync': typeof ApiPublicShopeeSyncRoute
  '/api/public/shopee/sync-ads': typeof ApiPublicShopeeSyncAdsRoute
  '/api/public/shopee/sync-carteira': typeof ApiPublicShopeeSyncCarteiraRoute
  '/api/public/shopee/sync-chat': typeof ApiPublicShopeeSyncChatRoute
  '/api/public/shopee/sync-escrow': typeof ApiPublicShopeeSyncEscrowRoute
  '/api/public/shopee/sync-produtos': typeof ApiPublicShopeeSyncProdutosRoute
  '/api/public/shopee/watchdog': typeof ApiPublicShopeeWatchdogRoute
  '/api/public/shopee/webhook': typeof ApiPublicShopeeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calculadora': typeof AuthenticatedCalculadoraRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dre': typeof AuthenticatedDreRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/api/chat': typeof ApiChatRoute
  '/ia/$conversaId': typeof AuthenticatedIaConversaIdRoute
  '/api/shopee/auth-url': typeof ApiShopeeAuthUrlRoute
  '/ia': typeof AuthenticatedIaIndexRoute
  '/api/public/shopee/callback': typeof ApiPublicShopeeCallbackRoute
  '/api/public/shopee/callback-ads': typeof ApiPublicShopeeCallbackAdsRoute
  '/api/public/shopee/dbg-chat': typeof ApiPublicShopeeDbgChatRoute
  '/api/public/shopee/refresh': typeof ApiPublicShopeeRefreshRoute
  '/api/public/shopee/refresh-token': typeof ApiPublicShopeeRefreshTokenRoute
  '/api/public/shopee/resumo-diario': typeof ApiPublicShopeeResumoDiarioRoute
  '/api/public/shopee/sync': typeof ApiPublicShopeeSyncRoute
  '/api/public/shopee/sync-ads': typeof ApiPublicShopeeSyncAdsRoute
  '/api/public/shopee/sync-carteira': typeof ApiPublicShopeeSyncCarteiraRoute
  '/api/public/shopee/sync-chat': typeof ApiPublicShopeeSyncChatRoute
  '/api/public/shopee/sync-escrow': typeof ApiPublicShopeeSyncEscrowRoute
  '/api/public/shopee/sync-produtos': typeof ApiPublicShopeeSyncProdutosRoute
  '/api/public/shopee/watchdog': typeof ApiPublicShopeeWatchdogRoute
  '/api/public/shopee/webhook': typeof ApiPublicShopeeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/calculadora': typeof AuthenticatedCalculadoraRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dre': typeof AuthenticatedDreRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/ia/$conversaId': typeof AuthenticatedIaConversaIdRoute
  '/api/shopee/auth-url': typeof ApiShopeeAuthUrlRoute
  '/_authenticated/ia/': typeof AuthenticatedIaIndexRoute
  '/api/public/shopee/callback': typeof ApiPublicShopeeCallbackRoute
  '/api/public/shopee/callback-ads': typeof ApiPublicShopeeCallbackAdsRoute
  '/api/public/shopee/dbg-chat': typeof ApiPublicShopeeDbgChatRoute
  '/api/public/shopee/refresh': typeof ApiPublicShopeeRefreshRoute
  '/api/public/shopee/refresh-token': typeof ApiPublicShopeeRefreshTokenRoute
  '/api/public/shopee/resumo-diario': typeof ApiPublicShopeeResumoDiarioRoute
  '/api/public/shopee/sync': typeof ApiPublicShopeeSyncRoute
  '/api/public/shopee/sync-ads': typeof ApiPublicShopeeSyncAdsRoute
  '/api/public/shopee/sync-carteira': typeof ApiPublicShopeeSyncCarteiraRoute
  '/api/public/shopee/sync-chat': typeof ApiPublicShopeeSyncChatRoute
  '/api/public/shopee/sync-escrow': typeof ApiPublicShopeeSyncEscrowRoute
  '/api/public/shopee/sync-produtos': typeof ApiPublicShopeeSyncProdutosRoute
  '/api/public/shopee/watchdog': typeof ApiPublicShopeeWatchdogRoute
  '/api/public/shopee/webhook': typeof ApiPublicShopeeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/calculadora'
    | '/chat'
    | '/configuracoes'
    | '/dashboard'
    | '/dre'
    | '/financeiro'
    | '/notificacoes'
    | '/pedidos'
    | '/precificacao'
    | '/produtos'
    | '/api/chat'
    | '/ia/$conversaId'
    | '/api/shopee/auth-url'
    | '/ia/'
    | '/api/public/shopee/callback'
    | '/api/public/shopee/callback-ads'
    | '/api/public/shopee/dbg-chat'
    | '/api/public/shopee/refresh'
    | '/api/public/shopee/refresh-token'
    | '/api/public/shopee/resumo-diario'
    | '/api/public/shopee/sync'
    | '/api/public/shopee/sync-ads'
    | '/api/public/shopee/sync-carteira'
    | '/api/public/shopee/sync-chat'
    | '/api/public/shopee/sync-escrow'
    | '/api/public/shopee/sync-produtos'
    | '/api/public/shopee/watchdog'
    | '/api/public/shopee/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/calculadora'
    | '/chat'
    | '/configuracoes'
    | '/dashboard'
    | '/dre'
    | '/financeiro'
    | '/notificacoes'
    | '/pedidos'
    | '/precificacao'
    | '/produtos'
    | '/api/chat'
    | '/ia/$conversaId'
    | '/api/shopee/auth-url'
    | '/ia'
    | '/api/public/shopee/callback'
    | '/api/public/shopee/callback-ads'
    | '/api/public/shopee/dbg-chat'
    | '/api/public/shopee/refresh'
    | '/api/public/shopee/refresh-token'
    | '/api/public/shopee/resumo-diario'
    | '/api/public/shopee/sync'
    | '/api/public/shopee/sync-ads'
    | '/api/public/shopee/sync-carteira'
    | '/api/public/shopee/sync-chat'
    | '/api/public/shopee/sync-escrow'
    | '/api/public/shopee/sync-produtos'
    | '/api/public/shopee/watchdog'
    | '/api/public/shopee/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/calculadora'
    | '/_authenticated/chat'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/dre'
    | '/_authenticated/financeiro'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pedidos'
    | '/_authenticated/precificacao'
    | '/_authenticated/produtos'
    | '/api/chat'
    | '/_authenticated/ia/$conversaId'
    | '/api/shopee/auth-url'
    | '/_authenticated/ia/'
    | '/api/public/shopee/callback'
    | '/api/public/shopee/callback-ads'
    | '/api/public/shopee/dbg-chat'
    | '/api/public/shopee/refresh'
    | '/api/public/shopee/refresh-token'
    | '/api/public/shopee/resumo-diario'
    | '/api/public/shopee/sync'
    | '/api/public/shopee/sync-ads'
    | '/api/public/shopee/sync-carteira'
    | '/api/public/shopee/sync-chat'
    | '/api/public/shopee/sync-escrow'
    | '/api/public/shopee/sync-produtos'
    | '/api/public/shopee/watchdog'
    | '/api/public/shopee/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiShopeeAuthUrlRoute: typeof ApiShopeeAuthUrlRoute
  ApiPublicShopeeCallbackRoute: typeof ApiPublicShopeeCallbackRoute
  ApiPublicShopeeCallbackAdsRoute: typeof ApiPublicShopeeCallbackAdsRoute
  ApiPublicShopeeDbgChatRoute: typeof ApiPublicShopeeDbgChatRoute
  ApiPublicShopeeRefreshRoute: typeof ApiPublicShopeeRefreshRoute
  ApiPublicShopeeRefreshTokenRoute: typeof ApiPublicShopeeRefreshTokenRoute
  ApiPublicShopeeResumoDiarioRoute: typeof ApiPublicShopeeResumoDiarioRoute
  ApiPublicShopeeSyncRoute: typeof ApiPublicShopeeSyncRoute
  ApiPublicShopeeSyncAdsRoute: typeof ApiPublicShopeeSyncAdsRoute
  ApiPublicShopeeSyncCarteiraRoute: typeof ApiPublicShopeeSyncCarteiraRoute
  ApiPublicShopeeSyncChatRoute: typeof ApiPublicShopeeSyncChatRoute
  ApiPublicShopeeSyncEscrowRoute: typeof ApiPublicShopeeSyncEscrowRoute
  ApiPublicShopeeSyncProdutosRoute: typeof ApiPublicShopeeSyncProdutosRoute
  ApiPublicShopeeWatchdogRoute: typeof ApiPublicShopeeWatchdogRoute
  ApiPublicShopeeWebhookRoute: typeof ApiPublicShopeeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precificacao': {
      id: '/_authenticated/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof AuthenticatedPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dre': {
      id: '/_authenticated/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof AuthenticatedDreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculadora': {
      id: '/_authenticated/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof AuthenticatedCalculadoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia/': {
      id: '/_authenticated/ia/'
      path: '/ia'
      fullPath: '/ia/'
      preLoaderRoute: typeof AuthenticatedIaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/shopee/auth-url': {
      id: '/api/shopee/auth-url'
      path: '/api/shopee/auth-url'
      fullPath: '/api/shopee/auth-url'
      preLoaderRoute: typeof ApiShopeeAuthUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ia/$conversaId': {
      id: '/_authenticated/ia/$conversaId'
      path: '/ia/$conversaId'
      fullPath: '/ia/$conversaId'
      preLoaderRoute: typeof AuthenticatedIaConversaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/shopee/webhook': {
      id: '/api/public/shopee/webhook'
      path: '/api/public/shopee/webhook'
      fullPath: '/api/public/shopee/webhook'
      preLoaderRoute: typeof ApiPublicShopeeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/watchdog': {
      id: '/api/public/shopee/watchdog'
      path: '/api/public/shopee/watchdog'
      fullPath: '/api/public/shopee/watchdog'
      preLoaderRoute: typeof ApiPublicShopeeWatchdogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/sync-produtos': {
      id: '/api/public/shopee/sync-produtos'
      path: '/api/public/shopee/sync-produtos'
      fullPath: '/api/public/shopee/sync-produtos'
      preLoaderRoute: typeof ApiPublicShopeeSyncProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/sync-escrow': {
      id: '/api/public/shopee/sync-escrow'
      path: '/api/public/shopee/sync-escrow'
      fullPath: '/api/public/shopee/sync-escrow'
      preLoaderRoute: typeof ApiPublicShopeeSyncEscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/sync-chat': {
      id: '/api/public/shopee/sync-chat'
      path: '/api/public/shopee/sync-chat'
      fullPath: '/api/public/shopee/sync-chat'
      preLoaderRoute: typeof ApiPublicShopeeSyncChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/sync-carteira': {
      id: '/api/public/shopee/sync-carteira'
      path: '/api/public/shopee/sync-carteira'
      fullPath: '/api/public/shopee/sync-carteira'
      preLoaderRoute: typeof ApiPublicShopeeSyncCarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/sync-ads': {
      id: '/api/public/shopee/sync-ads'
      path: '/api/public/shopee/sync-ads'
      fullPath: '/api/public/shopee/sync-ads'
      preLoaderRoute: typeof ApiPublicShopeeSyncAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/sync': {
      id: '/api/public/shopee/sync'
      path: '/api/public/shopee/sync'
      fullPath: '/api/public/shopee/sync'
      preLoaderRoute: typeof ApiPublicShopeeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/resumo-diario': {
      id: '/api/public/shopee/resumo-diario'
      path: '/api/public/shopee/resumo-diario'
      fullPath: '/api/public/shopee/resumo-diario'
      preLoaderRoute: typeof ApiPublicShopeeResumoDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/refresh-token': {
      id: '/api/public/shopee/refresh-token'
      path: '/api/public/shopee/refresh-token'
      fullPath: '/api/public/shopee/refresh-token'
      preLoaderRoute: typeof ApiPublicShopeeRefreshTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/refresh': {
      id: '/api/public/shopee/refresh'
      path: '/api/public/shopee/refresh'
      fullPath: '/api/public/shopee/refresh'
      preLoaderRoute: typeof ApiPublicShopeeRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/dbg-chat': {
      id: '/api/public/shopee/dbg-chat'
      path: '/api/public/shopee/dbg-chat'
      fullPath: '/api/public/shopee/dbg-chat'
      preLoaderRoute: typeof ApiPublicShopeeDbgChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/callback-ads': {
      id: '/api/public/shopee/callback-ads'
      path: '/api/public/shopee/callback-ads'
      fullPath: '/api/public/shopee/callback-ads'
      preLoaderRoute: typeof ApiPublicShopeeCallbackAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/callback': {
      id: '/api/public/shopee/callback'
      path: '/api/public/shopee/callback'
      fullPath: '/api/public/shopee/callback'
      preLoaderRoute: typeof ApiPublicShopeeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalculadoraRoute: typeof AuthenticatedCalculadoraRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDreRoute: typeof AuthenticatedDreRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPrecificacaoRoute: typeof AuthenticatedPrecificacaoRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedIaConversaIdRoute: typeof AuthenticatedIaConversaIdRoute
  AuthenticatedIaIndexRoute: typeof AuthenticatedIaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalculadoraRoute: AuthenticatedCalculadoraRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDreRoute: AuthenticatedDreRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPrecificacaoRoute: AuthenticatedPrecificacaoRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedIaConversaIdRoute: AuthenticatedIaConversaIdRoute,
  AuthenticatedIaIndexRoute: AuthenticatedIaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  ApiShopeeAuthUrlRoute: ApiShopeeAuthUrlRoute,
  ApiPublicShopeeCallbackRoute: ApiPublicShopeeCallbackRoute,
  ApiPublicShopeeCallbackAdsRoute: ApiPublicShopeeCallbackAdsRoute,
  ApiPublicShopeeDbgChatRoute: ApiPublicShopeeDbgChatRoute,
  ApiPublicShopeeRefreshRoute: ApiPublicShopeeRefreshRoute,
  ApiPublicShopeeRefreshTokenRoute: ApiPublicShopeeRefreshTokenRoute,
  ApiPublicShopeeResumoDiarioRoute: ApiPublicShopeeResumoDiarioRoute,
  ApiPublicShopeeSyncRoute: ApiPublicShopeeSyncRoute,
  ApiPublicShopeeSyncAdsRoute: ApiPublicShopeeSyncAdsRoute,
  ApiPublicShopeeSyncCarteiraRoute: ApiPublicShopeeSyncCarteiraRoute,
  ApiPublicShopeeSyncChatRoute: ApiPublicShopeeSyncChatRoute,
  ApiPublicShopeeSyncEscrowRoute: ApiPublicShopeeSyncEscrowRoute,
  ApiPublicShopeeSyncProdutosRoute: ApiPublicShopeeSyncProdutosRoute,
  ApiPublicShopeeWatchdogRoute: ApiPublicShopeeWatchdogRoute,
  ApiPublicShopeeWebhookRoute: ApiPublicShopeeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
