REVOKE ALL ON FUNCTION public.dashboard_kpis_periodo_impl(date, date, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.dashboard_serie_periodo_impl(date, date, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.dashboard_serie_horaria_impl(date, date, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.dashboard_top_produtos_periodo_impl(date, date, integer, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.dashboard_curva_abc_impl(date, date, integer, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.dashboard_kpis_periodo(date, date, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.dashboard_serie_periodo(date, date, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.dashboard_serie_horaria(date, date, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.dashboard_top_produtos_periodo(date, date, integer, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.dashboard_curva_abc(date, date, integer, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.dashboard_kpis_periodo(date, date, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.dashboard_serie_periodo(date, date, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.dashboard_serie_horaria(date, date, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.dashboard_top_produtos_periodo(date, date, integer, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.dashboard_curva_abc(date, date, integer, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.dashboard_kpis_periodo_impl(date, date, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.dashboard_serie_periodo_impl(date, date, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.dashboard_serie_horaria_impl(date, date, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.dashboard_top_produtos_periodo_impl(date, date, integer, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.dashboard_curva_abc_impl(date, date, integer, text) TO service_role;