DROP FUNCTION IF EXISTS public.dashboard_kpis_periodo(date, date);
DROP FUNCTION IF EXISTS public.dashboard_kpis_periodo_impl(date, date);
DROP FUNCTION IF EXISTS public.dashboard_serie_periodo(date, date);
DROP FUNCTION IF EXISTS public.dashboard_serie_periodo_impl(date, date);
DROP FUNCTION IF EXISTS public.dashboard_serie_horaria(date, date);
DROP FUNCTION IF EXISTS public.dashboard_serie_horaria_impl(date, date);
DROP FUNCTION IF EXISTS public.dashboard_curva_abc(date, date, integer);
DROP FUNCTION IF EXISTS public.dashboard_curva_abc_impl(date, date, integer);
DROP FUNCTION IF EXISTS public.dashboard_top_produtos_periodo(date, date, integer);
DROP FUNCTION IF EXISTS public.dashboard_top_produtos_periodo_impl(date, date, integer);
DROP FUNCTION IF EXISTS public.pedidos_detalhe(date, date, integer, integer, text, text);
DROP FUNCTION IF EXISTS public.pedidos_detalhe_impl(date, date, integer, integer, text, text);
DROP FUNCTION IF EXISTS public.pedidos_detalhe_totais(date, date, text, text);
DROP FUNCTION IF EXISTS public.pedidos_detalhe_totais_impl(date, date, text, text);
DROP FUNCTION IF EXISTS public.produtos_com_giro(date, date);